class_name CardDatabase
extends RefCounted

## Builds CardDefinitions from printed card data + rules scripts.
##
## Data sources, in order:
##   1. data/cards/cards.json — compact database generated by tools/extract_cards.py
##      from the deck lists. Loads instantly; this is what the game and training use.
##   2. data/raw/cards.csv (150 MB MTGJSON dump) — scanned only for names missing
##      from the JSON, and only when explicitly allowed (slow: several seconds).
##   3. Placeholder definition, so a game can still start with an unknown card.
##
## Rules come from CardLibrary (hand-written) or OracleParser (derived from text).

const JSON_PATH := "res://data/cards/cards.json"
const CSV_PATHS := [
	"res://data/raw/cards.csv/cards.csv",
	"res://data/raw/cards.csv",
]

static var card_cache: Dictionary = {}   # name_lowercase -> CardDefinition
static var _json_loaded: bool = false
static var _raw_rows: Dictionary = {}    # name_lowercase -> Dictionary (printed data)

## Allow the slow CSV scan for cards missing from cards.json.
static var allow_csv_fallback: bool = true


static func get_card_definition(card_name: String) -> CardDefinition:
	var key := card_name.to_lower().strip_edges()
	if card_cache.has(key):
		return card_cache[key]

	_load_json()
	if not _raw_rows.has(key) and allow_csv_fallback:
		_scan_csv_for([key])

	var def: CardDefinition
	if _raw_rows.has(key):
		def = _build_definition(_raw_rows[key])
	else:
		push_warning("CardDatabase: no data for '%s' — using a placeholder. Run tools/extract_cards.py." % card_name)
		def = CardDefinition.new()
		def.card_id = _make_id(key)
		def.card_name = card_name
		def.type_line = "Creature"
	card_cache[key] = def
	return def


## Load every card a deck list needs in one go (one CSV scan at most).
static func preload_names(names: PackedStringArray) -> void:
	_load_json()
	var missing: Array[String] = []
	for n in names:
		var key := n.to_lower().strip_edges()
		if not card_cache.has(key) and not _raw_rows.has(key):
			missing.append(key)
	if not missing.is_empty() and allow_csv_fallback:
		_scan_csv_for(missing)
	for n in names:
		get_card_definition(n)


## Kept for compatibility with older code paths — loads the JSON database.
static func load_cards_from_csv() -> void:
	_load_json()


# ───────────────────────────── Loading ─────────────────────────────

static func _load_json() -> void:
	if _json_loaded:
		return
	_json_loaded = true
	if not FileAccess.file_exists(JSON_PATH):
		push_warning("CardDatabase: %s not found — run tools/extract_cards.py" % JSON_PATH)
		return
	var file := FileAccess.open(JSON_PATH, FileAccess.READ)
	var data = JSON.parse_string(file.get_as_text())
	if typeof(data) != TYPE_DICTIONARY or not data.has("cards"):
		push_warning("CardDatabase: %s is not a valid card database" % JSON_PATH)
		return
	for row in data["cards"]:
		_raw_rows[str(row.get("name", "")).to_lower()] = row


static func _scan_csv_for(keys: Array) -> void:
	var path := ""
	for candidate in CSV_PATHS:
		if FileAccess.file_exists(candidate):
			path = candidate
			break
	if path.is_empty():
		return

	var wanted := {}
	for k in keys:
		wanted[k] = true

	var file := FileAccess.open(path, FileAccess.READ)
	if not file:
		return
	var headers := file.get_csv_line()
	var col: Dictionary = {}
	for i in range(headers.size()):
		col[headers[i]] = i
	var name_idx: int = col.get("name", -1)
	if name_idx == -1:
		return

	while not file.eof_reached() and not wanted.is_empty():
		var row := file.get_csv_line()
		if row.size() <= name_idx:
			continue
		var key := row[name_idx].to_lower()
		if not wanted.has(key):
			continue
		var side := _col(row, col.get("side", -1))
		if not side.is_empty() and side != "a":
			continue
		var data := {}
		for header in col.keys():
			data[header] = _col(row, col[header])
		_raw_rows[key] = data
		wanted.erase(key)


static func _col(row: PackedStringArray, idx: int) -> String:
	if idx == -1 or row.size() <= idx:
		return ""
	return row[idx]


# ───────────────────────────── Building ─────────────────────────────

static func _build_definition(row: Dictionary) -> CardDefinition:
	var def := CardDefinition.new()
	var c_name: String = str(row.get("name", ""))
	def.card_name = c_name
	def.card_id = _make_id(c_name.to_lower())
	def.mana_cost = str(row.get("manaCost", ""))
	def.parsed_cost = parse_mana_cost(def.mana_cost)
	def.mana_value = int(float(str(row.get("manaValue", "0"))))
	def.type_line = str(row.get("type", ""))
	def.subtypes = _split_list(str(row.get("subtypes", "")))
	def.supertypes = _split_list(str(row.get("supertypes", "")))
	def.colors = _split_list(str(row.get("colors", "")))
	def.oracle_text = str(row.get("text", ""))
	def.power = str(row.get("power", "")).to_int()
	def.toughness = str(row.get("toughness", "")).to_int()

	var types_str := str(row.get("types", ""))
	def.card_type = _determine_card_type(types_str if not types_str.is_empty() else def.type_line)

	var keywords: PackedStringArray = []
	for kw in _split_list(str(row.get("keywords", ""))):
		keywords.append(kw.to_lower())
	def.keywords = keywords

	if CardLibrary.has_script(c_name):
		def.rules = CardLibrary.get_script_for(c_name)
	else:
		def.rules = OracleParser.derive(def, str(row.get("producedMana", "")))
	return def


static func _split_list(value: String) -> PackedStringArray:
	var result: PackedStringArray = []
	for part in value.split(","):
		var p := part.strip_edges()
		if not p.is_empty():
			result.append(p)
	return result


static func _make_id(key: String) -> String:
	return key.replace(" ", "_").replace("'", "").replace(",", "")


static func _determine_card_type(type_str: String) -> CardDefinition.CardType:
	if "Land" in type_str:
		return CardDefinition.CardType.LAND
	if "Creature" in type_str:
		return CardDefinition.CardType.CREATURE
	if "Instant" in type_str:
		return CardDefinition.CardType.INSTANT
	if "Sorcery" in type_str:
		return CardDefinition.CardType.SORCERY
	if "Enchantment" in type_str:
		return CardDefinition.CardType.ENCHANTMENT
	if "Artifact" in type_str:
		return CardDefinition.CardType.ARTIFACT
	return CardDefinition.CardType.CREATURE


## "{1}{U}{R}" -> {"generic": 1, "U": 1, "R": 1}. Hybrid / phyrexian symbols count as generic.
static func parse_mana_cost(cost_str: String) -> Dictionary:
	var parsed: Dictionary = {}
	var regex := RegEx.create_from_string("\\{([^}]+)\\}")
	for m in regex.search_all(cost_str):
		var symbol: String = m.get_string(1)
		if symbol in MTGPlayer.COLORS:
			parsed[symbol] = parsed.get(symbol, 0) + 1
		elif symbol.is_valid_int():
			parsed["generic"] = parsed.get("generic", 0) + symbol.to_int()
		elif symbol == "X":
			continue
		else:
			parsed["generic"] = parsed.get("generic", 0) + 1
	return parsed
